# Generated by Django 5.1.4 on 2025-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cart_coupon_code_cart_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupons',
            field=models.ManyToManyField(related_name='products', to='products.coupon'),
        ),
    ]
