# Generated by Django 5.1.4 on 2025-02-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
