# Generated by Django 5.1.4 on 2025-03-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_order_items_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('RAZORPAY', 'Razorpay'), ('PAYPAL', 'PayPal')], max_length=100),
        ),
    ]
