# Generated by Django 5.1.4 on 2025-03-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_order_paypal_payment_id_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
