# Generated by Django 5.1.4 on 2025-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_order_paypal_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='new_items',
        ),
        migrations.AlterField(
            model_name='product',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='coupon_products', to='products.coupon'),
        ),
    ]
