# Generated by Django 5.1.4 on 2025-03-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
