# Generated by Django 5.1.4 on 2025-03-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0035_orderitem_cancel_reason_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return Requested', 'Return Requested'), ('Return Accepted', 'Return Accepted'), ('Return Rejected', 'Return Rejected')], default='Pending', max_length=50),
        ),
    ]
